export enum ActiveView {
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  DASHBOARD = 'DASHBOARD',
  EMPLOYEE = 'EMPLOYEE',
  CLIENT = 'CLIENT',
  PRODUCT = 'PRODUCT',
  SECTOR = 'SECTOR',
  PRODUCTION = 'PRODUCTION',
  RECOVERY = 'RECOVERY',
  FAQ = 'FAQ'
}